### ISSUE TITLE
Resume 링크 접근 불가능

### ISSUE THREAD

**Issue by Sn-Kinos** [GrassHopper42/GrassHopper42#1]
## 개요

`README.md` 에 있는 [Resume](https://www.notion.so/grasshopper42/fab701867e334fc4b16cfa5e647b52d9)링크가 노션 우측 상단의 공유 버튼을 통해 만들어진 링크가 아니라서 접근할 수 없는 문제가 발생합니다.

## 문제 재연

1. 노션 로그아웃 or 시크릿 탭 열기
2. 상단 Resume 링크 접속

## 해결 방안

<img width="518" alt="image" src="https://user-images.githubusercontent.com/26380261/223937280-ca06deab-2a1d-4cda-a300-ecd4ff0f5816.png">

노션 우측 상단의 `공유` > `웹에서 공유` 활성화 후 나오는 링크로 변경합니다.
> 노션 페이지의 제목이 바뀔 경우 공유 링크가 바뀔 수 있습니다.

**Comment by GrassHopper42** [comment]
감사합니다! 링크 새로 등록했고, 테스트도 해봤는데 이제 잘 됩니다.
